spring.application.name=ems-backend


spring.datasource.url=jdbc:postgresql://localhost:5432/ems_db
spring.datasource.username=postgres
spring.datasource.password=Root@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never

spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.default_schema=ems
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT
jwt.secret=ems_super_secret_key_for_jwt_authentication_2026_change_in_prod
jwt.expiration=86400000