-- ================================
-- RESET
-- ================================
DROP SCHEMA IF EXISTS ems CASCADE;
CREATE SCHEMA ems;

-- ================================
-- ENUM TYPES
-- ================================

CREATE TYPE ems.user_role AS ENUM ('ADMIN', 'STAFF');

CREATE TYPE ems.equipment_status AS ENUM ('ACTIVE', 'UNDER_MAINTENANCE', 'RETIRED');

CREATE TYPE ems.maintenance_status AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED');

CREATE TYPE ems.checkpoint_status AS ENUM ('PENDING', 'COMPLETED');


-- ================================
-- USERS TABLE
-- ================================

CREATE TABLE ems.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role ems.user_role NOT NULL DEFAULT 'STAFF',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);


-- ================================
-- EQUIPMENT TABLE
-- ================================

CREATE TABLE ems.equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    type VARCHAR(100) NOT NULL,
    status ems.equipment_status NOT NULL DEFAULT 'ACTIVE',
    purchase_date DATE NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_equipment_created_by 
        FOREIGN KEY (created_by) REFERENCES ems.users(id),

    CONSTRAINT fk_equipment_updated_by 
        FOREIGN KEY (updated_by) REFERENCES ems.users(id)
);


-- ================================
-- MAINTENANCE TABLE
-- ================================

CREATE TABLE ems.maintenance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    status ems.maintenance_status NOT NULL DEFAULT 'PENDING',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,

    completed_at TIMESTAMP,

    CONSTRAINT fk_maintenance_equipment 
        FOREIGN KEY (equipment_id) REFERENCES ems.equipment(id) ON DELETE CASCADE,

    CONSTRAINT fk_maintenance_created_by 
        FOREIGN KEY (created_by) REFERENCES ems.users(id),

    CONSTRAINT fk_maintenance_updated_by 
        FOREIGN KEY (updated_by) REFERENCES ems.users(id)
);


-- ================================
-- MAINTENANCE CHECKPOINT TABLE
-- ================================

CREATE TABLE ems.maintenance_checkpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maintenance_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    status ems.checkpoint_status NOT NULL DEFAULT 'PENDING',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,

    completed_by BIGINT,
    completed_at TIMESTAMP,

    CONSTRAINT fk_checkpoint_maintenance 
        FOREIGN KEY (maintenance_id) REFERENCES ems.maintenance(id) ON DELETE CASCADE,

    CONSTRAINT fk_checkpoint_created_by 
        FOREIGN KEY (created_by) REFERENCES ems.users(id),

    CONSTRAINT fk_checkpoint_updated_by 
        FOREIGN KEY (updated_by) REFERENCES ems.users(id),

    CONSTRAINT fk_checkpoint_completed_by 
        FOREIGN KEY (completed_by) REFERENCES ems.users(id)
);


-- ================================
-- INDEXES
-- ================================

CREATE INDEX idx_users_email ON ems.users(email);

CREATE INDEX idx_equipment_status ON ems.equipment(status);

CREATE INDEX idx_maintenance_status ON ems.maintenance(status);

CREATE INDEX idx_equipment_created_by ON ems.equipment(created_by);
CREATE INDEX idx_maintenance_equipment_id ON ems.maintenance(equipment_id);
CREATE INDEX idx_checkpoint_maintenance_id ON ems.maintenance_checkpoint(maintenance_id);

